blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import static

admin.site.site_header= 'Login employee'
admin.site.index_title='Welcome employees'
admin.site.site_title='Employees'
urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/core/urls.py
from django.urls import path
from .views import register, login_user, logout_user, user_profile, EmployeeCreateView, EmployeeListView, EmployeeUpdateView, EmployeeDeleteView, UserEditView, PostsList, PostsDetail, PostsEdit, PostsCreate, PostsDelete

urlpatterns = [
    path('', EmployeeListView.as_view(), name='home'),
    path('register/', register, name="register"),
    path('login/', login_user, name="login_user"),
    path('logout/', logout_user, name='logout_user'),
    path('profile/', user_profile, name='profile'),
    path('create/', EmployeeCreateView.as_view(), name='create'),
    path('update/<pk>', EmployeeUpdateView.as_view(), name='update'),
    path('delete/<pk>', EmployeeDeleteView.as_view(), name='update'),
    path('edituser/<pk>', UserEditView.as_view(), name='edit_user'),
    path('posts/', PostsList.as_view(), name='posts'),
    path('posts_detail/<slug:slug>/', PostsDetail.as_view(), name='posts_detail'),
    path('posts_edit/<slug:slug>', PostsEdit.as_view(), name='posts_edit'),
    path('posts_create/', PostsCreate.as_view(), name='posts_create'),
    path('posts_delete/<slug:slug>', PostsDelete.as_view(), name='posts_delete'),
]

blog/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
import django_filters


# Create your models here.

LABELS = (
    ('NEW', 'New'),
    ('SECOND', 'Second'),
    ('THIRD', 'Third')
)


class Employee(models.Model):
    name = models.CharField(max_length=150)
    department = models.CharField(max_length=150)
    phone = models.CharField(max_length=11)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    label = models.CharField(max_length=6, choices=LABELS, default='NEW')

    def __str__(self):
        return self.name


class User(AbstractUser):
    username = models.CharField(max_length=150)
    fullname = models.CharField(max_length=100, default='First Name, Last Name')
    email = models.CharField(verbose_name='email address', max_length=30, unique=True)
    phone = models.CharField(max_length=11, default='(xxx)xxxxxx',)
    mobile = models.CharField(max_length=11, default='+370xxxxxxx')
    job = models.CharField(max_length=50, default='Your current job')
    website = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='users', default='users/default.jpg')
    address = models.CharField(max_length=100, default='Street, City')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'address', 'phone']


STATUS = (
    (0, "Draft"),
    (1, "Publish"),
)


class Posts(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.EmailField(max_length=200, unique=True)
    updated = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(null=True, upload_to='posts', default='Image')


    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title


class PostFilter(django_filters.FilterSet):
    title = django_filters.CharFilter(lookup_expr='icontains')
    title__gt = django_filters.CharFilter(field_name='title', lookup_expr='gt')
    title__lt = django_filters.CharFilter(field_name='title', lookup_expr='lt')

    created = django_filters.NumberFilter(field_name='created', lookup_expr='date')
    created__gt = django_filters.NumberFilter(field_name='created', lookup_expr='date__gt')
    created__lt = django_filters.NumberFilter(field_name='created', lookup_expr='date__lt')

    class Meta:
        model = Posts
        fields = ['title', 'content', 'created', 'status']

blog/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Employee, User, Posts, STATUS



class RegisterForm(UserCreationForm):
    username = forms.CharField(help_text=False)
    email = forms.CharField(help_text=False)
    password1 = forms.CharField(widget=forms.PasswordInput(), help_text=False, label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput(), help_text=False, label='Confirm Password')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = ['name', 'department', 'phone', 'email', 'address']


class EditUserForm(forms.ModelForm):
    fullname = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(max_length=50)
    phone = forms.CharField(max_length=11)
    mobile = forms.CharField(max_length=11)
    job = forms.CharField(max_length=50)
    website = forms.CharField(max_length=100)
    photo = forms.ImageField(max_length=100)
    address = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ['fullname', 'email', 'phone', 'mobile', 'address', 'job', 'photo']


class PostsEditForm(forms.ModelForm):
    title = forms.CharField(max_length=200)
    slug = forms.SlugField(max_length=200)
    content = forms.CharField(max_length=10000)
    status = forms.ChoiceField(choices=STATUS)
    image = forms.ImageField(max_length=100)

    class Meta:
        model = Posts
        fields = ['title', 'slug', 'content', 'status', 'image']

blog/core/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import RegisterForm, EmployeeForm, PostsEditForm
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from .models import Employee, User, Posts, PostFilter


# Create your views here.


class EmployeeCreateView(LoginRequiredMixin, CreateView):
    model = Employee
    login_url = 'login_user'
    form_class = EmployeeForm
    template_name = 'create.html'
    success_url = '/'


class EmployeeListView(ListView):
    model = Employee
    login_url = 'login_user'
    template_name = 'index.html'
    success_url = '/'
    paginate_by = 2


class EmployeeUpdateView(LoginRequiredMixin, UpdateView):
    model = Employee
    login_url = 'login_user'
    form_class = EmployeeForm
    template_name = 'update.html'
    success_url = '/'


class EmployeeDeleteView(LoginRequiredMixin, DeleteView):
    model = Employee
    login_url = 'login_user'
    template_name = 'delete.html'
    success_url = '/'


class UserEditView(UpdateView):
    model = User
    login_url = 'login_user'
    template_name = 'edituser.html'
    success_url = '/'
    fields = ['fullname', 'email', 'phone', 'mobile', 'address', 'job', 'photo']


def register(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('login_user')
    else:
        form = RegisterForm()

    return render(request, 'register.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Your account is not active")
        else:
            return HttpResponse("Your username or password is incorrect! Please try again")

    return render(request, 'index.html', {})


def logout_user(request):
    logout(request)
    return redirect('home')


def user_profile(request):
    return render(request, 'profile.html')


def edit_user(request):
    return render(request, 'edituser.html')


class PostsList(ListView):
    model = Posts
    template_name = 'posts.html'
    success_url = '/'

    def post_list(self, request):
        f = PostFilter(request.GET, queryset=Posts.objects.all())
        return render(request, 'posts.html', {'filter': f})

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['items'] = Posts.objects.filter(created__date__range=("2022-06-19", "2022-06-19"))
    #     return context


class PostsDetail(DetailView):
    model = Posts
    template_name = 'posts_detail.html'


class PostsEdit(UpdateView):
    model = Posts
    form_class = PostsEditForm
    template_name = 'posts_edit.html'
    success_url = reverse_lazy('posts')


class PostsCreate(CreateView):
    model = Posts
    form_class = PostsEditForm
    template_name = 'posts_create.html'
    success_url = reverse_lazy('posts')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostsDelete(DeleteView):
    model = Posts
    template_name = 'posts_delete.html'
    success_url = reverse_lazy('posts')


def product_list(request):
    f = PostFilter(request.GET, queryset=Posts.objects.all())
    return render(request, 'posts.html', {'filter': f})

blog/core/templates/base.html
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Django practice blog project</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'modal.css' %}">
    <script src="{% static 'modaljs.js' %}"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
<style>
body {
    color: #404E67;
    background: moccasin;
    font-family: 'Open Sans', sans-serif;
}
.table-wrapper {
    width: 700px;
    margin: 30px auto;
    background: #fff;
    padding: 20px;
    box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.table-title {
    padding-bottom: 10px;
    margin: 0 0 10px;
}
.table-title h2 {
    margin: 6px 0 0;
    font-size: 22px;
}
.table-title .add-new {
    float: right;
    height: 30px;
    font-weight: bold;
    font-size: 12px;
    text-shadow: none;
    min-width: 100px;
    border-radius: 50px;
    line-height: 13px;
}
.table-title .add-new i {
    margin-right: 4px;
}
table.table {
    table-layout: fixed;
}
table.table tr th, table.table tr td {
    border-color: #e9e9e9;
}
table.table th i {
    font-size: 13px;
    margin: 0 5px;
    cursor: pointer;
}
table.table th:last-child {
    width: 100px;
}
table.table td a {
    cursor: pointer;
    display: inline-block;
    margin: 0 5px;
    min-width: 24px;
}
table.table td a.add {
    color: #27C46B;
}
table.table td a.edit {
    color: #FFC107;
}
table.table td a.delete {
    color: #E34724;
}
table.table td i {
    font-size: 19px;
}
table.table td a.add i {
    font-size: 24px;
    margin-right: -1px;
    position: relative;
    top: 3px;
}
table.table .form-control {
    height: 32px;
    line-height: 32px;
    box-shadow: none;
    border-radius: 2px;
}
table.table .form-control.error {
    border-color: #f50000;
}
table.table td .add {
    display: none;
}
</style>


</head>
<body>
{% block content %}
{% endblock %}


</body>

blog/core/templates/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{% include 'navigation.html' %}
<div>
  <form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary"  type="submit" value="Submit">
  </form>
</div>
{% endblock %}

blog/core/templates/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{% include 'navigation.html' %}
<div>
  <form method="post">
  {% csrf_token %}
  {{form}}
  <h1>Are you sure you want to delete?</h1>
  <input class="btn btn-primary baton"  type="submit" value="Delete">
  </form>
</div>
{% endblock %}

blog/core/templates/edituser.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{% include 'navigation.html' %}
{% if user.is_authenticated %}

<div class="container">
    <div class="main-body">

          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{user.photo.url}}" alt="User photo" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{user.fullname}}</h4>
                      <p class="text-secondary mb-1">{{user.job}}</p>
                      <p class="text-muted font-size-sm">{{user.address}}</p>
                      <button class="btn btn-primary">Follow</button>
                      <button class="btn btn-outline-primary">Message</button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                    <span class="text-secondary">https://bootdey.com</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
                    <span class="text-secondary">bootdey</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                    <span class="text-secondary">@bootdey</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                    <span class="text-secondary">bootdey</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                    <span class="text-secondary">bootdey</span>
                  </li>
                </ul>
              </div>
            </div>
            <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input class="btn btn-primary baton"  type="submit" value="Update">
  </form>
          </div>

        </div>
    </div>

{% else %}

  <p>Please login</p>
  <a href="{% url 'login_user' %}">Log In</a>
{% endif %}

{% endblock %}

blog/core/templates/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}


{% endblock %}

blog/core/templates/navigation.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <img class="navbar-brand" src="{% static 'images/QSMVo.gif' %}" alt="My image" width="80" height="90">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="../profile/">Profile</a>
        </li>
        {% if user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="/admin/">Administration</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link disabled"></a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="/posts/">Posts</a>
        </li>
          <li class="nav-item">
          <p class="nav-link disabled" >Logged-in as: {{user}}</p>
          </li>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout_user' %}" class="nav-link">Logout</a>
        </li>
        {% else %}
        <li>
          <div class="container" style="margin-left: 40px;position:relative;bottom: 29px">
            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#loginModal">
              Login
            </button>
          </div>
          <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header border-bottom-0">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="form-title text-center">
                    <h4>Login</h4>
                  </div>
                  <div class="d-flex flex-column text-center">
                    <form action="/login/" method="post" >
                      {% csrf_token %}
                      <div class="form-group" >
                        <input type="email" style="text-transform: lowercase" class="form-control" id="email1" autocomplete="off" placeholder="Your email address..." name="username">
                      </div>
                      <div class="form-group">
                        <input type="password" class="form-control" id="password1" placeholder="Your password..." name="password">
                      </div>
                      <button type="submit" style="display: flex; align-items: center; font-family: inherit; font-weight: 500; margin-left: 125px;
  font-size: 16px;
  padding: 0.7em 1.4em 0.7em 1.1em;
  color: white;
  background: #ad5389;
  background: linear-gradient(0deg, rgba(20,167,62,1) 0%, rgba(102,247,113,1) 100%);
  border: none;
  box-shadow: 0 0.7em 1.5em -0.5em #14a73e98;
  letter-spacing: 0.05em;
  border-radius: 20em;
  cursor: pointer;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
" value="Login">Login</button>
                    </form>
                </div>
              </div>
                <div class="modal-footer d-flex justify-content-center">
                  <div class="signup-section">Not a member yet? <a href="{% url 'register' %}" class="text-info"> Sign Up</a>.</div>
                </div>
            </div>
          </div>
            </div>
        </li>

        {% endif %}
        <form class="form-inline position-relative" style=margin-left:300px>
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

blog/core/templates/posts.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{% include 'navigation.html' %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 left">
            <h1>Posts</h1>
            <form method="get">
        {{ filter.form.as_p }}
        <input type="submit" />
    </form>
    {% for obj in filter.qs %}
        {{ obj.title }} - ${{ obj.created }}<br />
            {% endfor %}
            <form method="get" action="{% url 'posts_create' %}">
        <button class="btn btn-primary hBack" type="submit">Create post</button>
        </form>
            {% for post in posts_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <img src="{{post.image.url}}" alt="..." class="img-thumbnail" style="width: 100px;height: 100px">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'posts_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}

  <p>Please login</p>
  <a href="{% url 'login_user' %}">Log In</a>
{% endif %}

{% endblock %}

blog/core/templates/posts_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{% include 'navigation.html' %}
{% if user.is_authenticated %}
 <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}

  <input class="btn btn-primary baton"  type="submit" value="Create">
  </form>
{% else %}

  <p>Please login</p>
  <a href="{% url 'login_user' %}">Log In</a>
{% endif %}

{% endblock %}

blog/core/templates/posts_delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{% include 'navigation.html' %}
<div>
  <form method="post">
  {% csrf_token %}
  {{form}}
  <h1>Are you sure you want to delete?</h1>
  <input class="btn btn-primary baton"  type="submit" value="Delete">
  </form>
</div>
{% endblock %}

blog/core/templates/posts_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{% include 'navigation.html' %}
{% if user.is_authenticated %}
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <img src="{{posts.image.url}}" alt="..." class="img-thumbnail" style="width: 200px;height: 200px">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ posts.author }} | {{ posts.created }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
        <br>

        <a class="btn btn-info " href="{% url 'posts_edit' posts.slug %}">Edit</a>
        <br>
        <form method="get" action="{% url 'posts' %}">
        <button class="btn btn-primary hBack" type="submit">Back to Posts</button>
        </form>
        <form method="get" action="{% url 'posts_delete' posts.slug %}">
        <button class="btn btn-primary hBack" type="submit">Delete post</button>
        </form>
      </div>
    </div>
  </div>
</div>


{% else %}

  <p>Please login</p>
  <a href="{% url 'login_user' %}">Log In</a>
{% endif %}

{% endblock %}

blog/core/templates/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{% include 'navigation.html' %}
<div>
  <form method="post">
  {% csrf_token %}
  {{form}}
  <input class="btn btn-primary baton"  type="submit" value="Update">
  </form>
</div>
{% endblock %}